### ISSUE TITLE
where do you host the orchestrator?

### ISSUE THREAD

**Issue by bhomass** [Substra/orchestrator#134]
I can see the backend and frontend installed on the system used by the data owners and data scientist. The orchestrator seems to be an independent piece all by itself. Who is supposed to host this orchestrator? In a federated environment, how do you get one organization to own this orchestrator piece?

**Comment by RomainGoussault** [comment]
Hi, Yes hospital must deploy a backend (and optionally a frontend).
The orchestrator can be hosted anywhere, it can be alone or co-located with one of the backend.
